Support for XML embedded in text
jeroenterheerdt/pycsspeechtts pull request #15
Opened 2021-01-15 20:40 UTC by daniele-athome

This tries to address #14, although I want to hear your opinion on this approach. It is somewhat a "breaking" change in the sense that if invalid XML is passed in the text the code will now throw an exception, unlike before.

Other possible approaches would be:

* another boolean parameter denoting XML text or plain text (xml_text=True/False)
* fallback to plain (escaped) text in case of parsing errors

Maybe I'm just being excessively careful, but since this library is used by the Microsoft TTS Home Assistant component I would be careful introducing this change.

2021-02-15 16:38 UTC, daniele-athome commented
Hey there! Any chance this will be merged? Or we could start a conversation on the points I made in the initial comment maybe.

2021-02-16 17:39 UTC, jeroenterheerdt commented
sorry for my late response. I would do both: add the parameter, make sure it is optional and has a good default. also, implement the fall back.

2021-02-16 17:39 UTC, jeroenterheerdt requested changes
implement fallback

2021-07-07 19:58 UTC, rsegers commented on src/pycsspeechtts/pycsspeechtts.py
> +            prosody.append(ElementTree.fromstring(text))
```suggestion
            voice.append(ElementTree.XML('<prosody>'+text+'</prosody>'))
            prosody = voice.find('prosody')
            prosody.set('rate', rate)
            prosody.set('volume', volume)
            prosody.set('pitch', pitch)
            prosody.set('contour', contour)
```

I had the same request: being able to use embedded XML. The lines of code above allows for using XML tags inside the text, whilst also remaining backward compatible with a regular string. 

For example, all of these work:

- `This is a regular, backwards compatible sentence`
- `This is a sentence with a <break time="2s" /> long pause`
- `<p>Sentence 1 in paragraph 1.</p><p>Sentence 2 in paragraph 2</p>`

(oh and to be clear: this replaces lines 71 up to and including 76)

2021-07-15 18:41 UTC, closed without merging